// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ResearchUSAPI;
using System;

namespace ResearchUSAPI.Migrations
{
    [DbContext(typeof(ResearchUSContext))]
    partial class ResearchUSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ResearchUSAPI.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_on");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("last_login");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
